### ISSUE TITLE
Running in Docker on OSX gives java.lang.UnsatisfiedLinkError: 'long io.tiledb.libtiledb.tiledbJNI.new_tiledb_config_tpp()'

### ISSUE THREAD

**Issue by mosabdullah** [TileDB-Inc/TileDB-Java#309]
Related to https://github.com/TileDB-Inc/TileDB-Java/issues/154

Hi, 

I am working on an Apple silicon M2 Mac using IntelliJ, gradle and Kotlin to prototype a TileDB Spring Boot application. Using the dependency  _**implementation("io.tiledb:tiledb-java:0.17.9")**_ works fine when running from IntelliJ; however, when I deploy to a docker image, I get the UnsatisfiedLinkError mentioned in the title of this issue. 

I have also manually added the native libraries and linked them to ensure they are there, but this still fails. I use other native libs for a DDS library, which works fine. 

Below are my Dockerfile and Docker Compose sections and some screenshots. 

```yaml
  myservice:
    container_name: myservice
    build:
      context: ./../myservice
      dockerfile: OSX.Dockerfile
    environment:
      - APPLICATION_LOG_LEVEL=debug
      - LD_LIBRARY_PATH=/usr/lib
```

```Dockerfile
FROM azul/zulu-openjdk-debian:17-latest

VOLUME /tmp
ADD build/libs/*.jar /app/

# include all the native libs required
ADD build/lib/darwin-x86_64 /usr/lib

ENV LD_LIBRARY_PATH /usr/lib

ENTRYPOINT [ "sh", "-c", \
             "java \
             -Djava.security.egd=file:/dev/./urandom \
             -jar /app/myservice.jar" \
]
```
![tiledb-libs](https://github.com/TileDB-Inc/TileDB-Java/assets/195180/7479b84a-2796-4ca4-9aa2-fd8cba38ed4e)

Note: I extracted the tiledb-java.jar because I thought it wasn't having the native libs inside the jar file. This doesn't seem to work either. 

The following are the files inside the docker image.

![docker-image-files](https://github.com/TileDB-Inc/TileDB-Java/assets/195180/da81ee4f-079f-47b7-beda-96918bf1c127)

I have exhausted all avenues at this point. Do you have any examples, or do you see any problems with the above configurations?

A final note: The application.jar deployed into docker also includes the tiledb-java.jar as a lib/dependency inside that jar, which I believe should be the way that it is done.

 

Thanks. 

Mo

**Comment by mosabdullah** [comment]
Hi Dimitris, 

I have extracted and provided screenshots of the jar file with some comments.

This is the main folder. It is a spring boot jar, hence the given structure.

![Screenshot 2023-09-25 at 09 18 24](https://github.com/TileDB-Inc/TileDB-Java/assets/195180/48f55563-30a6-4015-bf23-adba873984d4)

The next one shows all the libraries included, including the tiledb jar file, as highlighted.

![Screenshot 2023-09-25 at 09 20 20](https://github.com/TileDB-Inc/TileDB-Java/assets/195180/d1c70cc3-e4b4-4c9c-b42e-5acdecbb38c2)

The screenshots below show the jar class packages with code, spring boot code, etc.

<img width="986" alt="Screenshot 2023-09-25 at 09 27 11" src="https://github.com/TileDB-Inc/TileDB-Java/assets/195180/8c8d6cbd-a1dd-4688-adf5-ebbdcc768339">

<img width="495" alt="Screenshot 2023-09-25 at 09 27 18" src="https://github.com/TileDB-Inc/TileDB-Java/assets/195180/f03c5cd8-949a-436d-b3c4-31caa3271031">

Please let me know if you require anything further.

**Comment by DimitrisStaratzis** [comment]
Could you please try to run this simple example that I made? It runs ok for me so it should at least tell us if there is an issue with your set up. 

Best, 
Dimitris 
[tiledb-example-5.zip](https://github.com/TileDB-Inc/TileDB-Java/files/12717072/tiledb-example-5.zip)


To run simply do:

```
 ./gradlew clean build
 docker build -t my-spring-boot-app .
 docker run my-spring-boot-app
```

**Comment by mosabdullah** [comment]
Hey @DimitrisStaratzis 

I get the following error. The same problem I get with my application.

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.1)

2023-09-25T22:11:24.928Z  INFO 1 --- [           main] c.e.t.TiledbExampleApplicationKt         : Starting TiledbExampleApplicationKt using Java 17.0.8.1 with PID 1 (/app/app.jar started by root in /app)
2023-09-25T22:11:24.929Z  INFO 1 --- [           main] c.e.t.TiledbExampleApplicationKt         : No active profile set, falling back to 1 default profile: "default"
2023-09-25T22:11:25.159Z  INFO 1 --- [           main] c.e.t.TiledbExampleApplicationKt         : Started TiledbExampleApplicationKt in 0.392 seconds (process running for 0.662)
2023-09-25T22:11:25.768Z  WARN 1 --- [           main] io.tiledb.libtiledb.NativeLibLoader      : Could not load Native TIleDB
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.UnsatisfiedLinkError: 'long io.tiledb.libtiledb.tiledbJNI.new_tiledb_config_tpp()'
        at io.tiledb.libtiledb.tiledbJNI.new_tiledb_config_tpp(Native Method)
        at io.tiledb.libtiledb.tiledb.new_tiledb_config_tpp(tiledb.java:660)
        at io.tiledb.java.api.Config.<init>(Config.java:68)
        at io.tiledb.java.api.Context.<init>(Context.java:69)
        at com.example.tiledbexample.TiledbExampleApplicationKt.main(TiledbExampleApplication.kt:14)
        ... 8 more

```

**Comment by mosabdullah** [comment]
I have uninstalled Docker Desktop and only installed the Docker Engine via an emulator as mentioned [here](https://opennms.discourse.group/t/how-to-run-containers-without-docker-desktop-for-mac-running-with-apple-silicon-arm-architecture/2917). 

The same problem exists.

**Comment by DimitrisStaratzis** [comment]
I have used an intel Mac to create the example. I will also run it in an arm based Mac soon and get back to you. 

Best, 
Dimitris

**Comment by mosabdullah** [comment]
It runs fine on my Personal Intel Mac.

**Comment by DimitrisStaratzis** [comment]
Building Dockerfiles on Mac M1 can fail because they are built by default for `linux/arm64` instead of `linux/amd64` architecture. This can lead to packages missing when installing dependencies on your docker image. 

Fortunately, Docker can locally build images for a different architecture using the `buildx` client plugin.

## Install

You can find the installation instructions here: https://docs.docker.com/build/buildx/install/

`buildx` is included in Docker desktop installation and placed in `/Applications/Docker.app/Contents/Resources/cli-plugins/docker-buildx`

You just need to copy this file to `~/.docker/cli-plugins`

```bash
mkdir ~/.docker/cli-plugins
cp /Applications/Docker.app/Contents/Resources/cli-plugins/docker-buildx ~/.docker/cli-plugins
```

## Test installation

```bash
$ docker buildx ls
NAME/NODE DRIVER/ENDPOINT STATUS  PLATFORMS
default * docker                  
  default default         running linux/arm64, linux/amd64, linux/riscv64, linux/ppc64le, linux/s390x, linux/arm/v7, linux/arm/v6
```

## Build

You first need to create a [Docker container driver](https://docs.docker.com/build/building/drivers/docker-container/)(https://docs.docker.com/build/building/drivers/docker-container/)

```bash
docker buildx create \
  --name container \
  --driver=docker-container
```

Now you can build your container for `linux/amd64`

```bash
docker buildx build --load --platform linux/amd64 -t <tag> -f <Dockerfile> --builder=container . 
```

**Comment by mosabdullah** [comment]
@DimitrisStaratzis, are the above `docker buildx` commands still required with the 0.19.0 release? I have tried both with and without these commands and I am still having the same issues, using your provided example.

**Comment by DimitrisStaratzis** [comment]
Yes, the 0.19.X release added the Apple Silicon native libs in the jar. This is however irrelevant to what you are trying to do here. Could you please specify at which step they are encountering the issue?

Best, 
Dimitris

**Comment by mosabdullah** [comment]
I am running the example you provided above with updated dependency now to tiledb-java 0.19.1. I get the following error still

`
2023-10-22T21:12:25.977Z  INFO 1 --- [           main] c.e.t.TiledbExampleApplicationKt         : Starting TiledbExampleApplicationKt using Java 17.0.8.1 with PID 1 (/app/app.jar started by root in /app)
2023-10-22T21:12:25.978Z  INFO 1 --- [           main] c.e.t.TiledbExampleApplicationKt         : No active profile set, falling back to 1 default profile: "default"
2023-10-22T21:12:26.262Z  INFO 1 --- [           main] c.e.t.TiledbExampleApplicationKt         : Started TiledbExampleApplicationKt in 0.471 seconds (process running for 0.689)
2023-10-22T21:12:27.162Z  WARN 1 --- [           main] io.tiledb.libtiledb.NativeLibLoader      : Could not load Native TIleDB
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.UnsatisfiedLinkError: 'long io.tiledb.libtiledb.tiledbJNI.new_tiledb_config_tpp()'
        at io.tiledb.libtiledb.tiledbJNI.new_tiledb_config_tpp(Native Method)
        at io.tiledb.libtiledb.tiledb.new_tiledb_config_tpp(tiledb.java:660)
        at io.tiledb.java.api.Config.<init>(Config.java:68)
        at io.tiledb.java.api.Context.<init>(Context.java:69)
        at com.example.tiledbexample.TiledbExampleApplicationKt.main(TiledbExampleApplication.kt:14)
        ... 8 more

`

**Comment by DimitrisStaratzis** [comment]
Hi @mosabdullah,

The Java API version you are using should not make any difference. Let me clarify a few things. 

We introduced version 0.19.0 with native support specifically tailored for Apple silicon. Following this, we rolled out a patch, 0.19.1, addressing some minor issues.

It's important to note that these updates shouldn't impact your current task. You're in the process of creating a Linux Docker container, meaning it exclusively utilizes Linux libraries, not native Mac ones. The challenge arises because our Linux native libraries are compiled for amd64, but your Mac, equipped with an arm processor, builds the Dockerfiles for arm64. To overcome this, follow the steps outlined in my previous response.

I hope this explanation clears up any confusion.

Best regards,
Dimitris

**Comment by mosabdullah** [comment]
Thanks @DimitrisStaratzis,

I had tried it previously, but not on the latest version. Anyway, I have tried it again and got the following issue.

```
2023-10-24 07:34:08 2023-10-23T21:34:08.248Z  INFO 1 --- [           main] c.e.t.TiledbExampleApplicationKt         : Starting TiledbExampleApplicationKt using Java 17.0.8.1 with PID 1 (/app/app.jar started by root in /app)
2023-10-24 07:34:08 2023-10-23T21:34:08.251Z  INFO 1 --- [           main] c.e.t.TiledbExampleApplicationKt         : No active profile set, falling back to 1 default profile: "default"
2023-10-24 07:34:09 2023-10-23T21:34:09.111Z  INFO 1 --- [           main] c.e.t.TiledbExampleApplicationKt         : Started TiledbExampleApplicationKt in 1.394 seconds (process running for 2.282)
2023-10-24 07:34:10 #
2023-10-24 07:34:10 # A fatal error has been detected by the Java Runtime Environment:
2023-10-24 07:34:10 #
2023-10-24 07:34:10 #  SIGILL (0x4) at pc=0x00007fff7d2901a1, pid=1, tid=6
2023-10-24 07:34:10 #
2023-10-24 07:34:10 # JRE version: OpenJDK Runtime Environment Zulu17.44+53-CA (17.0.8.1+1) (build 17.0.8.1+1-LTS)
2023-10-24 07:34:10 # Java VM: OpenJDK 64-Bit Server VM Zulu17.44+53-CA (17.0.8.1+1-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
2023-10-24 07:34:10 # Problematic frame:
2023-10-24 07:34:10 # C  [libtiledb.so+0x3241a1]  _GLOBAL__sub_I_heap_profiler.cc+0x31
2023-10-24 07:34:10 #
2023-10-24 07:34:10 # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
2023-10-24 07:34:10 #
2023-10-24 07:34:10 # An error report file with more information is saved as:
2023-10-24 07:34:10 # /app/hs_err_pid1.log
2023-10-24 07:34:10 #
2023-10-24 07:34:10 # If you would like to submit a bug report, please visit:
2023-10-24 07:34:10 #   http://www.azul.com/support/
2023-10-24 07:34:10 # The crash happened outside the Java Virtual Machine in native code.
2023-10-24 07:34:10 # See problematic frame for where to report the bug.
2023-10-24 07:34:10 #
2023-10-24 07:34:10 
2023-10-24 07:34:10 [error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007fffffdc7602]
2023-10-24 07:34:10 
```

I have tried several different JDKs in the Dockerfile, and all have the same issue.

[hs_err_pid1.log](https://github.com/TileDB-Inc/TileDB-Java/files/13079531/hs_err_pid1.log)

**Comment by ihnorton** [comment]
Hi @mosabdullah, it looks like you might not be putting `libtiledb.so` and `libtiledbjni.so` in the correct directory in order to be found by tiledb-java. If you could create a small, _fully self-contained_ example then we will be able to debug further. This needs to be a zip/tar file containing a `Dockerfile`, and all other files referenced inside the dockerfile -- right now,  the example [here](https://github.com/TileDB-Inc/TileDB-Java/issues/309#issue-1908067203) contains a number of external references from the working directory.

**Comment by mosabdullah** [comment]
Thanks, @ihnorton. I used the example that @DimitrisStaratzis [provided above](https://github.com/TileDB-Inc/TileDB-Java/issues/309#issuecomment-1733977088) but updated the tiledb-java version number to the latest. I was unaware I would need to include the above-mentioned libraries manually.

I will give this another go and get back to you on this.

**Comment by DimitrisStaratzis** [comment]
Hi @mosabdullah , 
Please try to run the example that I have sent you in this conversation (```tiled-example-5.zip```) but this time use [this](https://drive.google.com/file/d/1lTz7KURMy3vRDvHFRFGIXckEkzDBVxD3/view?usp=sharing) TileDB-Java jar instead of the one uploaded to maven central. 

More specifically. 

1. Build the project with the new jar
```
./gradlew clean build
```
2. Use buildx as intructed above

```
docker buildx create \
  --name container \
  --driver=docker-container 
```

```
docker buildx build --load --platform linux/amd64 -t <tag> -f <Dockerfile> --builder=container . 
```
3. Run
```
docker run <tag>
```

Let me know how it goes.

Best, 
Dimitris

**Comment by mosabdullah** [comment]
Hey @DimitrisStaratzis,

That worked. 

```text
2023-11-08 11:24:58 
2023-11-08 11:24:58   .   ____          _            __ _ _
2023-11-08 11:24:58  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
2023-11-08 11:24:58 ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2023-11-08 11:24:58  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
2023-11-08 11:24:58   '  |____| .__|_| |_|_| |_\__, | / / / /
2023-11-08 11:24:58  =========|_|==============|___/=/_/_/_/
2023-11-08 11:24:58  :: Spring Boot ::                (v3.1.1)
2023-11-08 11:24:58 
2023-11-08 11:24:59 2023-11-08T01:24:59.050Z  INFO 1 --- [           main] c.e.t.TiledbExampleApplicationKt         : Starting TiledbExampleApplicationKt using Java 17.0.2 with PID 1 (/app/app.jar started by root in /app)
2023-11-08 11:24:59 2023-11-08T01:24:59.052Z  INFO 1 --- [           main] c.e.t.TiledbExampleApplicationKt         : No active profile set, falling back to 1 default profile: "default"
2023-11-08 11:24:59 2023-11-08T01:24:59.938Z  INFO 1 --- [           main] c.e.t.TiledbExampleApplicationKt         : Started TiledbExampleApplicationKt in 1.423 seconds (process running for 2.394)
2023-11-08 11:25:01 TileDB v2.17.4
```

**Comment by DimitrisStaratzis** [comment]
Hi @mosabdullah, 
Great news! We will publish a new release with the fix very soon. I will keep you posted here. 

Best, 
Dimitris
